### ISSUE TITLE
Error: Cannot find module 'cross-fetch'

### ISSUE THREAD

**Issue by Huynheddie** [NikosNtigas/MMM-MALList#1]
Getting this error when trying to run Magic Mirror. Attached a picture (sorry for the low quality, couldn't get a screenshot)
![136372953_431463644570402_998414876012794176_n](https://user-images.githubusercontent.com/30208265/104267042-b7ea6300-5445-11eb-9353-a016fd6192a6.jpg)

**Comment by NikosNtigas** [comment]
First of all, are you using Magic Mirror latest release?
I checked where the cross-fetch is located and it is under the MagicMirror/mode_modules/
(MagicMirror/node_modules/cross-fetch/index.d.ts)
I don't know yet why this error occurred, when I npm run start this error does not print.
And It could be really helpful if you copy paste this error cause the image resolution is very low quality as you said.

**Comment by Huynheddie** [comment]
Yeah, I'm currently using the latest release. Here's a better image:
![image](https://user-images.githubusercontent.com/30208265/104395712-31458c80-54fe-11eb-8432-324fbf608e3b.png)

**Comment by NikosNtigas** [comment]
Could you please check if you have the cross-fetch folder under the node_modules folder?

**Comment by Huynheddie** [comment]
That was the issue! I installed it and everything works fine, thanks!
